# Arrays (1-D Arrays)
Arrays are a collection of elements of the same datatype

<img width = 1000 src = 'arrays-as-macrons.png'/>

## Types of Arrays
<img width = 1000 src = 'types-of-arrays.png'/>

## Arrays in Memory
<img width = 1000 src = 'arrays-in-1D.png'/>

<img width = 1000 src = 'arrays-in-2D.png'/>

<img width = 1000 src = 'arrays-in-3D.png'/>

## Initialising an array (1 Dimensional)
1. Using Array model
2. Using Numpy model

In [2]:
import array
my_array = array.array('i') # i stands for integer
my_array
# we've initialised an empty array, Time & Space Complexity = O(1)

array('i')

In [3]:
my_array1 = array.array('i', [1,2,3,4,5,6,67,7,8,9,10])
my_array1
# for an array of size 'n' , Time & Space Complexity = O(n)

array('i', [1, 2, 3, 4, 5, 6, 67, 7, 8, 9, 10])

In [4]:
import numpy as np
np_array = np.array([], dtype=int)
np_array
# we've initialised an empty array, Time & Space Complexity = O(1)

array([], dtype=int32)

In [5]:
np_array1 = [1,2,3,4,5,6,7,8,9]
np_array1
# for an array of size 'n' , Time & Space Complexity = O(n)

[1, 2, 3, 4, 5, 6, 7, 8, 9]

## Inserting an element
We have the option to insert an element either in the front, back or the middle of the array

In [6]:
my_array = array.array('i', [1,2,3,4])
print(my_array)

# inserting
my_array.insert(1, 6)       # (index, value)
my_array
'''
as we can see when we insert any element the existing elements after the index to which the value is inserted have to shift right. So the time complexity depends upon THE NO. OF ELEMENTS SHIFTING RIGHT. 
So, in the worst case - when we have to insert an element in the beginning the complexity will be O(N)
Space Complexity = O(1) -- because when we are inserting an element in an array, we only need one place for the element
'''

array('i', [1, 2, 3, 4])


'\nas we can see when we insert any element the existing elements after the index to which the value is inserted have to shift right. So the time complexity depends upon THE NO. OF ELEMENTS SHIFTING RIGHT. \nSo, in the worst case - when we have to insert an element in the beginning the complexity will be O(N)\nSpace Complexity = O(1) -- because when we are inserting an element in an array, we only need one place for the element\n'

In [7]:
my_array

array('i', [1, 6, 2, 3, 4])

## Traversing and accessing an element

In [8]:
# function -1 for traversal (preferred)
for i in my_array:
    print(i)

print('\n\nIf printed with index')
# function-2 for traversal
for i in range(0, len(my_array)):
    print(f'{my_array[i]} at index {i}')

'''
Time Complexity = O(N)
Space Complexity = O(1) because we dont need an extra location
'''


### writing a function for traversal
def traverseArray(array):
    for i in array:
        print(i)

1
6
2
3
4


If printed with index
1 at index 0
6 at index 1
2 at index 2
3 at index 3
4 at index 4


In [9]:
### to access an element
def accessElement(array, index):
    if index >= len(my_array):
        print(f'index doesnt exist. There are only {len(my_array)} elements in the array')
    else:
        print(f'The element at index {index} is {array[index]}')

accessElement(my_array, 5)

'''
Time and Space Complexity = O(1) Since we only look the element whose index is mentioned and we dont need any extra space for that
'''

index doesnt exist. There are only 5 elements in the array


'\nTime and Space Complexity = O(1) Since we only look the element whose index is mentioned and we dont need any extra space for that\n'

In [10]:
len(my_array)

5

In [11]:
my_array

array('i', [1, 6, 2, 3, 4])

## Searching in Array
 - Linear Search

In [12]:
my_array = array.array('i', [1,2,3,4,5])

def searchElement(array, to_find):
    for i in range(len(array)):
        if array[i] == to_find:
            print('found')
            break
    print('not found')
    # return -1

    
searchElement(my_array, 10)

'''
Time complexity = O(N)
Space complexity = O(1)
'''

not found


'\nTime complexity = O(N)\nSpace complexity = O(1)\n'

## Deletion in Arrays
Time Complexity = O(N)
Space = O(1)

In [56]:
my_array = array.array('i', [1,2,3,4,5])
my_array.remove(4)
my_array

array('i', [1, 2, 3, 5])

# Time Complexities of all operations in 1D Array
<img width = 1000 src = 'time-complexities-1D-array.png'/>

# 2-D Arrays
## Creating a 2-D array

In [1]:
import numpy as np
twoDArray = np.array([[1,2,3,4],
                      [5,6,7,8],
                      [9,10,11,12],
                      [13,14,15,16]])

print(twoDArray)
'''
time complexity & space Complexity = O(mn) --------- m = no. of rows, n= no. of columns
'''

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


## Insertion - Two Dimensional array
Two ways - 
- Adding Column `axis = 1`
- Adding Row `axis = 0`

<img width = 1000 src = '2D-array-insertion-columns.png'/>
<img width = 1000 src = '2D-array-insertion-rows.png'/>

In [6]:
twoDArray1 = np.array([[12,23,34,45],
                       [56,67,78,89],
                       [90,9,98,87],
                       [76,65,54,43]])

print(twoDArray1)

new_twodDArray1 = np.insert(twoDArray1, 0, [[1,2,3,4]], axis=1) # updates as column
# new_twodDArray1 = np.insert(twoDArray1, 0, [[11,22,33,44]], axis=0) # update as row
print(new_twodDArray1)


[[12 23 34 45]
 [56 67 78 89]
 [90  9 98 87]
 [76 65 54 43]]
[[ 1 12 23 34 45]
 [ 2 56 67 78 89]
 [ 3 90  9 98 87]
 [ 4 76 65 54 43]]


Using `np.insert()`, we can specify which column no. or which row no. we want to insert.

`np.insert(array name to insert in, row/column no. , array to insert, axis - whether column or row)`

<br>

If we know that we want to insert an element at the very end of a colummn or a row. The we use the `append()` method

In [8]:
new_twodDArray2 = np.append(twoDArray1, [[11,22,33,44]], axis=0)
new_twodDArray2

## Accessing an element in 2D Array

How to determine the no. of rows and no. of columns in a 2-D Array?

no. of rows = len(array)

no. of columns = len(array[0]) ------ basically the length of first row

In [11]:
twoDArray1

array([[12, 23, 34, 45],
       [56, 67, 78, 89],
       [90,  9, 98, 87],
       [76, 65, 54, 43]])

In [14]:
def accessElements(array, rowIndex, colIndex):
    if rowIndex >= len(array) or colIndex >= len(array[0]):
        print(f'Index out of range. There are {len(array)} rows and {len(array)[0]} columns')
    else: 
        print(array[rowIndex][colIndex])

accessElements(twoDArray1, 1,1)

'''
Time and Space Complexity = O(1)
'''

67


## Array Traversal in 2D Arrays

In [15]:
twoDArray1

array([[12, 23, 34, 45],
       [56, 67, 78, 89],
       [90,  9, 98, 87],
       [76, 65, 54, 43]])

In [20]:
def traversal2DArray(array):
    for i in range(0,len(array)):
        for j in range(0,len(array[0])):
            print(array[i][j], end=' ')
        print('\n')

traversal2DArray(twoDArray1)

'''
Time Complexity = O(mn)             m = # of rows, n = # of cols
Space Complexity = O(1)
'''

12 23 34 45 

56 67 78 89 

90 9 98 87 

76 65 54 43 



'\nTime Complexity = O(mn)             m = # of rows, n = # of cols\nSpace Complexity = O(1)\n'

## Searching in 2D Array

In [21]:
twoDArray1

array([[12, 23, 34, 45],
       [56, 67, 78, 89],
       [90,  9, 98, 87],
       [76, 65, 54, 43]])

In [28]:
def searchElement2DArray(array, to_find):
    for i in range(len(array)):
        for j in range(len(array[0])):
            if array[i][j] == to_find:
                print('Element found!')
                return 1
            
    return -1
    
       

searchElement2DArray(twoDArray1, 43)

'''
Time Complexity = O(mn)
Space complexity = O(1)
'''

Element found!


1

## Deletion in 2D Arrays
What exactly happens in deletion?

The python program basically creates a new variable and stores the elements of the existing array other than the deleted elements
<img width = 1000 src = 'deletion-2D-arrays.png'/>


In [29]:
new_deleted_array = np.delete(twoDArray1, 0, axis=0)
print(new_deleted_array)

'''
Time Complexity = O(mn) - because you need to copy all the elements from the existing array to a new array
Space Complexity = O(mn) - because we are creating a new variable in the memory
'''

[[56 67 78 89]
 [90  9 98 87]
 [76 65 54 43]]


<img width = 1000 src = 'time-and-space-complexity-2D-arrays.png'/>

<img src = 'use-or-avoid-arrays.png'/>